# Generated by Django 5.2.1 on 2025-06-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='personajes/'),
        ),
    ]
